name: nbehbc
channels:
- defaults
dependencies:
- python=3.6
- pip
- numpy
- scipy
- matplotlib
- vtk>=8
- ipython
- jupyter
- pip:
  - mne
  - traits
  - traitsui
  - pyface
  - mayavi
  - pysurfer
  - "https://github.com/wmvanvliet/conpy/zipball/master"
